In [1]:
import numpy as np

In [2]:
print(np.array([
    [[1, 2, 3, 4], [5, 6, 7, 8]], 
    [[2, 4, 6, 8], [10, 12, 14, 16]], 
    [[1, 3, 5, 7], [9, 11, 13, 15]] 
         ]))

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 2  4  6  8]
  [10 12 14 16]]

 [[ 1  3  5  7]
  [ 9 11 13 15]]]


In [5]:
print(np.ones((4,2,4), dtype='int'))

[[[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]]


In [7]:
print(np.zeros((3,2,4), dtype='int'))

[[[0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]]]


In [9]:
print(np.full((3,2,4),5))

[[[5 5 5 5]
  [5 5 5 5]]

 [[5 5 5 5]
  [5 5 5 5]]

 [[5 5 5 5]
  [5 5 5 5]]]


In [10]:
# 1d-array
arr_1d = np.array([1, 2, 3, 4])

# 2d-array
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8]]) 

# 3d-array
arr_3d = np.array([
    [[1, 2, 3, 4], [5, 6, 7, 8]], 
    [[2, 4, 6, 8], [10, 12, 14, 16]], 
    [[1, 3, 5, 7], [9, 11, 13, 15]]
    ])


In [14]:
print(arr_1d.shape)
print(arr_2d.shape)
print(arr_3d.shape)

(4,)
(2, 4)
(3, 2, 4)


In [16]:
print(arr_1d.size)
print(arr_2d.size)
print(arr_3d.size)

4
8
24


In [20]:
print(arr_1d.ndim)
print(arr_2d.ndim)
print(arr_3d.ndim)

1
2
3


In [23]:
# 인덱싱
# 1d-array객체 생성
arr_1d = np.array([1, 2, 3, 4, 5])

In [24]:
print(arr_1d[0])

1


In [25]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 7],
                   [6, 8, 9],
                   [11, 17, 19]]) # 4행 3열

In [29]:
print(arr_2d[0,-1])

3


In [30]:
print(arr_2d[-1,0])

11
